project:
  type: website
  output-dir: docs

website:
  # title: "Blog"
  navbar:
    right:
      - about.qmd
    left:
      - text: "Home"
        file: index.qmd
format:
  html:
    theme: cosmo
    css: styles.css



