project:
  type: website
  output-dir: docs

website:
  # title: "Blog"
  navbar:
    right:
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/tom-shlomo/
      - icon: github
        text: Github
        href: https://github.com/tomshlomo
      - icon: google
        text: Google Scholar
        href: https://scholar.google.com/citations?user=ZJSZgpwAAAAJ&hl=en
    left:
      - text: "Home"
        file: index.qmd
format:
  html:
    theme: cosmo
    css: styles.css



