project:
  type: website
  output-dir: docs

website:
  title: "Tom Shlomo's Blog"
  description: "Tom Shlomo's blog"
  site-url: https://tomshlomo.github.io/blog/
  navbar:
    right:
      - icon: linkedin
        # text: LinkedIn
        href: https://www.linkedin.com/in/tom-shlomo/
      - icon: github
        # text: Github
        href: https://github.com/tomshlomo
      - text: "{{< ai google-scholar size=Large >}}"
        href: https://scholar.google.com/citations?user=ZJSZgpwAAAAJ&hl=en
      - icon: rss
        href: index.xml
    # left:
    #   - text: "Home"
    #     file: index.qmd
format:
  html:
    theme: darkly
    css: styles.css



